// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA191IopownG_YGzkmjgxPQ5JVBFFv7vsg',
    appId: '1:697222573880:android:1735c75006fac9fe11dbcd',
    messagingSenderId: '697222573880',
    projectId: 'bwa-flutix-73c0b',
    storageBucket: 'bwa-flutix-73c0b.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA191IopownG_YGzkmjgxPQ5JVBFFv7vsg',
    appId: '1:697222573880:android:1735c75006fac9fe11dbcd',
    messagingSenderId: '697222573880',
    projectId: 'bwa-flutix-73c0b',
    storageBucket: 'bwa-flutix-73c0b.appspot.com',
    iosClientId: '599030350718-rt5diuiggpna5fmco6k05teqm2km0f66.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutix',
  );
}